# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-14 10:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='City')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'City',
            },
        ),
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Orgnazition Name')),
                ('desc', models.TextField(verbose_name='Orgnazition Description')),
                ('click_nums', models.IntegerField(default=0, verbose_name='Click Numbers')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='Fav number')),
                ('image', models.ImageField(upload_to='org/%Y/%m', verbose_name='Image')),
                ('address', models.CharField(max_length=150, verbose_name='Address')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.City', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Orgnazition Info',
                'verbose_name_plural': 'Orgnazition Info',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Teacher Name')),
                ('work_years', models.IntegerField(default=0, verbose_name='Work Years')),
                ('work_company', models.CharField(max_length=50, verbose_name='Work Company')),
                ('work_postion', models.CharField(max_length=50, verbose_name='Work Postion')),
                ('points', models.CharField(max_length=50, verbose_name='Points')),
                ('click_nums', models.IntegerField(default=0, verbose_name='Click Numbers')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='Fav number')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='CourseOrg')),
            ],
            options={
                'verbose_name': 'Teacher Info',
                'verbose_name_plural': 'Teacher Info',
            },
        ),
    ]
