# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-17 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_banner_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banner/%Y/%m', verbose_name='\u56fe\u50cf'),
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='\u7535\u5b50\u90ae\u4ef6'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6),
        ),
    ]
