# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-17 22:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170517_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Send Time'),
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', 'Register'), ('forget', 'Forget Password')], max_length=20, verbose_name='Code Type'),
        ),
    ]
