# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-18 09:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(verbose_name='Comments')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
            ],
            options={
                'verbose_name': 'User Comment',
                'verbose_name_plural': 'User Comment',
            },
        ),
        migrations.CreateModel(
            name='UserAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('mobile', models.CharField(max_length=11, verbose_name='Mobile')),
                ('course_name', models.CharField(max_length=50, verbose_name='Course Name')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
            ],
            options={
                'verbose_name': 'User Ask',
                'verbose_name_plural': 'User Ask',
            },
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
            ],
            options={
                'verbose_name': 'User Course',
                'verbose_name_plural': 'User Course',
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_id', models.IntegerField(default=0, verbose_name='Favorite')),
                ('fav_type', models.IntegerField(choices=[(1, 'Course Favorite'), (2, 'Teacher Favorite'), (3, 'Orgination Favorite')], verbose_name='Favorite Type')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
            ],
            options={
                'verbose_name': 'User Favorite',
                'verbose_name_plural': 'User Favorite',
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0, verbose_name='Users')),
                ('message', models.CharField(max_length=200, verbose_name='User Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
            ],
            options={
                'verbose_name': 'User Message',
                'verbose_name_plural': 'User Message',
            },
        ),
    ]
